function menuList(){

    const menus = [
        {
            label:"几何体",
            type:"Geometry",
            children:[
                {
                    label:"圆弧1",
                    content:"Arc1",
                    args:{
                        degree:0,
                        color:'rgba(255, 255, 255, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                },
                {
                    label:"圆弧2",
                    content:"Arc2",
                    args:{
                        p1:{x:0,y:0,z:0},
                        p2:{x:0,y:0,z:0},
                        p3:{x:0,y:0,z:0},
                        color:'rgba(19, 206, 102, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                },
                {
                    label:"cube",
                    content:"Cube",
                    args:{
                        color:'rgba(255, 255, 255, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                },
                {
                    label:"二维线段",
                    content:"Line2D",
                    args:{
                        p1:{x:0,y:0,z:0},
                        p2:{x:0,y:0,z:0},
                        color:'rgba(255, 255, 255, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                },
                {
                    label:"三维线段",
                    content:"Line3D",
                    args:{
                        p1:{x:0,y:0,z:0},
                        p2:{x:0,y:0,z:0},
                        p3:{x:0,y:0,z:0},
                        color:'rgba(255, 255, 255, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                    
                },
                {
                    label:"section",
                    content:"Section",
                    args:{
                        color:'rgba(255, 255, 255, 0.8)',
                        translate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        rotate:{
                            x:0,
                            y:0,
                            z:0
                        },
                        scale:{
                            x:1,
                            y:1,
                            z:1
                        }
                    },
                    customArgs:[],
                }
            ]
        },
        {
            label:"运算组件",
            type:"Operation",
            children:[
                {
                    label:"并集",
                    content:"Union",
                    args:{
                        A:null,
                        B:null,
                        // target:null
                    },
                    customArgs:[],
                },
                {
                    label:"交集",
                    content:"Intersect",
                    args:{
                        A:null,
                        B:null,
                        // target:null
                    },
                    customArgs:[],
                },
                {
                    label:"差集",
                    content:"Difference",
                    args:{
                        A:null,
                        B:null,
                        // target:null
                    },
                    customArgs:[],
                },
                {
                    label:"组合",
                    content:"Combine",
                    args:{
                        A:null,
                        B:null,
                        // target:null
                    },
                    customArgs:[],
                },
                {
                    label:"放置",
                    content:"Place",
                    args:{
                        // target:[]
                        A:null,
                    },
                    customArgs:[],
                }
            ]
        },
        {
          label:"数值组件",
          type:"Number",
          children:[
            {
                label:"数值",
                content:"Number",
                value:10
            }
          ]
        },
        {
            label:"数值运算组件",
            type:"NumberOperation",
            children:[
                {
                    label:"add",
                    content:"Add",
                    args:{A:0,B:0},
                    alge:"+"
                },
                {
                    label:"sub",
                    content:"Sub",
                    args:{A:0,B:0},
                    alge:"-"
                },
                {
                    label:"mul",
                    content:"Mul",
                    args:{A:0,B:0},
                    alge:"*"
                },
                {
                    label:"divide",
                    content:"Add",
                    args:{A:0,B:0},
                    alge:"/"
                }
            ]
        },
        {
            label:"属性组件",
            type:"Props",
            children:[
                {
                    label:"平移",
                    content:"translation",
                    value:[
                        {prop:"x",value:0},
                        {prop:"y",value:0},
                        {prop:"z",value:0},
                    ]
                },
                {
                    label:"旋转",
                    content:"rotate",
                    value:[
                        {prop:"x",value:0},
                        {prop:"y",value:0},
                        {prop:"z",value:0},
                    ]
                },
                {
                    label:"缩放",
                    content:"scale",
                    value:[
                        {prop:"x",value:0},
                        {prop:"y",value:0},
                        {prop:"z",value:0},
                    ]
                },
                {
                    label:"长",
                    content:"long",
                    value:[{prop:"long",value:0}]
                },
                {
                    label:"宽",
                    content:"width",
                    value:[{prop:"width",value:0}]
                },
                {
                    label:"高",
                    content:"height",
                    value:[{prop:"height",value:0}]
                },
                {
                    label:"颜色",
                    content:"color",
                    value:[
                        {prop:"r",value:0},
                        {prop:"g",value:0},
                        {prop:"b",value:0},
                        {prop:"a",value:1},
                    ]
                },
                {
                    label:"透明度",
                    content:"alpha",
                    value:[
                        {prop:"r",value:0},
                        {prop:"g",value:0},
                        {prop:"b",value:0},
                        {prop:"a",value:1},
                    ] 
                }
            ]
        }
    ]

    return menus
}

export default menuList()